# General information
seed: 1001
__set_seed: !apply:torch.manual_seed [!ref <seed>]
root: !PLACEHOLDER
tokenizers_folder: !ref <root>/tokenizers

# Hyparameters below are dependant on the attack and model used 
# and should be changed at the user's discretion
# -------------------------------------------------------------
# Attack information
max_decr: 1
eps: 0.1
nb_iter: 50
const: 10
lr: 0.05

target_sentence:
   - UP
attack_class: !name:robust_speech.adversarial.attacks.cw.ASRCarliniWagnerAttack
   targeted: True
   decrease_factor_eps: 0.5
   eps: !ref <eps>
   global_max_length: 562480
   initial_rescale: 1.0
   learning_rate: !ref <lr>
   optimizer: !name:torch.optim.SGD
   max_iter: !ref <nb_iter>
   const: !ref <const>
   train_mode_for_backward: True
   max_num_decrease_eps: !ref <max_decr>
save_audio: True
attack_name: cwsc
load_audio: False
# Model information
model_name: wav2vec1-SC-1012
source_model_name: !ref <model_name>

target_brain_class: !name:robust_speech.models.wav2vec2_fine_tune.W2VASR
target_brain_hparams_file: !ref model_configs/wav2vec1/<model_name>.yaml
source_brain_class: !name:robust_speech.models.wav2vec2_fine_tune.W2VASR
source_brain_hparams_file: !ref model_configs/wav2vec1/<source_model_name>.yaml

# Tokenizer information (compatible with target and source)
tokenizer: !new:speechbrain.dataio.encoder.CTCTextEncoder
pretrained_tokenizer_path: !ref <root>/trainings/wav2vec2-base-960h
# -------------------------------------------------------------

# Pretrainer loading parameters
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <tokenizers_folder>/<model_name>
   loadables:
      tokenizer: !ref <tokenizer>
   paths:
      tokenizer: !ref <pretrained_tokenizer_path>/tokenizer.ckpt

output_folder: !ref <root>/attacks/<attack_name>/<source_model_name>/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>
log: !ref <output_folder>/log.txt
save_audio_path: !ref <output_folder>/save

dataset_prepare_fct: !name:robust_speech.data.speech_commands.prepare_speech_commands
dataio_prepare_fct: !name:robust_speech.data.dataio.dataio_prepare

# Data files
data_folder: !ref <root>/data/SpeechCommands 
csv_folder: !ref <data_folder>/csv 
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded

test_splits: ["testing"]
skip_prep: True
ckpt_interval_minutes: 15 # save checkpoint every N min
test_csv:
   - !ref <data_folder>/csv/testing-100.csv
avoid_if_longer_than: 2.0
avoid_if_shorter_than: 0.0

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80

# Decoding parameters (only for text_pipeline)
blank_index: 0
bos_index: 1
eos_index: 2

test_dataloader_opts:
    batch_size: 1

logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <log>
