# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  no_epoch_checkpoints: false
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr

dataset:
  num_workers: 1
  max_tokens: 500000
  max_tokens_valid: 600000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: dev_clean

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 3

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_epoch: 100
  clip_norm: 5.0
  update_freq: [4]
  lr: [0.00005]
  sentence_avg: true

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08
  weight_decay: 0.0

lr_scheduler:
  _name: tri_stage
  warmup_steps: 50000
  hold_steps: 350000
  decay_steps: 500000

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: False
  mask_prob: 0.5
  mask_channel_prob: 0.1
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
  no_pretrained_weights: True
